### ISSUE TITLE
Styling Slides: Größerer Titel, größerer Slogan

### ISSUE THREAD

**Issue by xwolfde** [ilifau/ili-fau-templates#31]
Der Titel soll deutlich vergrößert werden. (Etwa verdoppelt). Ebenso der Slogan darunter.

Zudem soll der Hintergrund hinter der Schrift von Titel und Slogan entfallen. Stattdessen bitte die Schriftfarbe in Weiß und der Schrift einen 
```text-shadow: 1px 2px 2px black```
geben, damit dieser auch vor wechselnden Hintergrund erkannbar ist.

Für die Hover/Focus-Eigenschaft ggf. die Schriftfarbe wechseln oder eine andere geeignete Optik nutzen.

**Comment by SebastianHonert** [comment]
Done. Bei der weißen Schrift bin ich etwas skeptisch, da müssen die Motive schon relativ dunkel sein.

**Comment by SebastianHonert** [comment]
Ist dieselbe Schriftgröße, bloß die Auflösung ist bei Dir höher. In Relation zur Breite des Container ist die Schrift gleich groß. Ich würde einfach noch Media Queries für >=1600 und/oder >= 1920 einbauen.

**Comment by xwolfde** [comment]
ah...

[ok. Notiere: ILI und UL muss verpflichtend mit großen bzw. neuen Bildschirmen/Laptops mit großen Auflösungen ausgestattet werden. >:) ]

**Comment by SebastianHonert** [comment]
Oder wir machen die Schriftgröße gleich abhängig vom Viewport mit vw? Oder ist das zu fortschrittlich? [https://caniuse.com/#feat=viewport-units](https://caniuse.com/#feat=viewport-units)

**Comment by xwolfde** [comment]
Indirekte Antwort: Bei dem Theme lassen wir den Autoprefixer das CSS um Vendorcodes ergänzen. Dabei haben wir eingestellt, daß wir Browserversionen nur bis maximal 3 Jahre zurück unterstützen.
In anderen Worten: Leute, die Browser nutzen, welche länger als 3 Jahre nicht aktuallisiert wurden, müssen mit Problemen rechnen. Die nehmen wir in Kauf, zumal mangelhafte Browserupdates ein Fall für die IT Sicherheit sind :P

**Comment by xwolfde** [comment]
Ich glaub dieser Issue kann zu?  (auch wenn ich Issues angestoßen hab, ist es IMHO an den Repo-Besitzer zu entscheiden, ob/wann er sie schließt; da mag ich nicht einfach zumachen, wenn es nicht mein Repo ist.)
