### ISSUE TITLE
Darstellung auf Mobile bei zu langen Titeln 

### ISSUE THREAD

**Issue by xwolfde** [ilifau/ili-fau-templates#45]
Hier ist ein Problem. 
Siehe Screenshot: 
![Screenshot_20191001-090634](https://user-images.githubusercontent.com/1070669/65945741-e4d35c00-e434-11e9-835a-fd47aae2472e.png)

Linke Pfeile weg, Text bricht nicht um (wordwrap nicht passend gesetzt?), Höhe nicht vertikal mittig.

**Comment by SebastianHonert** [comment]
Alte Version? Das Problem sollte mit dem letzten Update schon gefixt sein. Kannst du das noch einmal testen? Ansonsten: Welche Display-Größe ist das?

WordWrap passe ich an, solange nicht von Donaudampfschifffahrtsgesellschaftskapitänen die Rede ist, sollte es aber passen.

Ich spreche auch noch einmal mit der Webredaktion. Grundsätzlich sollten die Titel kurz sein und längere Texte als Untertitel ergänzt werden. Das ist a) visuell ansprechender und b) inhaltlich fokussierter. Eventuell sollten wir die maximale Länge der Texte in den Eingabefeldern begrenzen?

**Comment by SebastianHonert** [comment]
Ja, muss eine alte Version sein (vgl. die Größe der Buttons unter dem Bild).

**Comment by SebastianHonert** [comment]
![image](https://user-images.githubusercontent.com/7110206/65953567-857d4800-e444-11e9-909b-ad8033c50200.png)

So sieht das aktuell aus (Chrome, Firefox, Safari, Chrome bzw. Brave auf Android).

**Comment by xwolfde** [comment]
Jupp.  Besser 
![Screenshot_20191001-121322](https://user-images.githubusercontent.com/1070669/65953934-50bdc080-e445-11e9-9f49-e66b1945db72.png)

**Comment by SebastianHonert** [comment]
Klassischer Fall von "Sticky Hover" (https://stackoverflow.com/questions/17233804/how-to-prevent-sticky-hover-effects-for-buttons-on-touch-devices), :focus war aber auch aktiv. Update soeben gepusht.

**Comment by xwolfde** [comment]
Update drin
