### ISSUE TITLE
Kontrast/Shadow oder Border verstärken

### ISSUE THREAD

**Issue by xwolfde** [ilifau/ili-fau-templates#46]
Bei Bildern mit hellen oder weißen Hintergrund erscheint die Schrift des Titels oftmals nicht  kontraststark genug.
Hier wäre ggf. ein stärkerer Shadow bei der Schrift hilfreich?

![grafik](https://user-images.githubusercontent.com/1070669/66551087-4b8ffe00-eb36-11e9-9e6b-61010dda340f.png)

**Comment by SebastianHonert** [comment]
Ich habe den Textschatten ein wenig vergrößert. Es gibt auch bereits die Möglichkeit, einen halbtransparenten Hintergrund vor die Slides zu legen (FAU-blau oder schwarz), um die Lesbarkeit zu verbessern (auf https://refresh2018.cms.rrze.uni-erlangen.de/ ist das aktiviert). Vorschläge für Schatten und Overlay sowie das Verhältnis zwischen den beiden Komponenten nehme ich gerne entgegen. Auch eine Variante mit einem Linear Gradient wäre denkbar, ähnlich wie bei den Infoboxen (vgl. Screenshot). Dann wäre der untere Teil im Hintergrund etwas abgedunkelt, der obere Teil bliebe unberührt.

<img width="1440" alt="fau-linear-gradient" src="https://user-images.githubusercontent.com/7110206/66574158-0b4f7080-eb74-11e9-9699-972af902ae76.png">

**Comment by xwolfde** [comment]
Das mit dem semitransparenten Hintergrund hatten wir ja am Anfang auch, wurde aber von der Projektleiterin ausdrücklich abgelehnt. Schwierig. Muss man sich rantasten.

**Comment by SebastianHonert** [comment]
Bezog sich die Ablehnung auch auf den Vorschlag mit dem Gradienten oder auf einen zentrierten Hintergrund über dem Slider-Content (also eine Art "Box")? Das fände ich auch nicht so ansehnlich. Den Entwurf mit dem Gradienten finde ich aber eigentlich recht schick. Er ließe sich auch mit wenig Aufwand per CSS-Änderung übernehmen. Vielleicht sollte ich Cathrin bitten, eine Meinung dazu bei der Projektleitung einzuholen?

**Comment by xwolfde** [comment]
Meiner Erinnerung nach auf den Background von Überschriften und Slogans im Slider.
Aber das war vor fast ein Jahr!
Ob das heute noch gilt, ist eine andere Frage.

Ich selbst bin da leidenschaftslos. Hauptsache mein A11Y-Tester meckert mich nicht an :))

**Comment by SebastianHonert** [comment]
Das letzte Update (0.0.8) ermöglicht einen linearen Farbverlauf hinter den Überschriften. Wir werden das irgendwann so ausbauen, dass Slides individuell konfiguriert werden können. Sehen wir uns am 6. November? Da könnten wir das Thema Finanzierung/Wartungsbedarf zumindest kurz anschneiden.
