### ISSUE TITLE
Hypens

### ISSUE THREAD

**Issue by xwolfde** [ilifau/ili-fau-templates#47]
Ich würde vorschlagen, dem h3 der Slider-Titel ein "hypens: none" zu vergeben um den Default zu überschreiben.

(Default im Theme sind h1,h2 mit Hypens none ausgestattet, h3-6 sind jedoch hypens: auto)

![ili-slider-hypens](https://user-images.githubusercontent.com/1070669/68202487-c0324d00-ffbb-11e9-9268-351856670f97.jpg)

**Comment by SebastianHonert** [comment]
Gute Idee, ist erledigt.
