### ISSUE TITLE
Function rausnehmen oder if function drum herum machen

### ISSUE THREAD

**Issue by xwolfde** [ilifau/ili-fau-templates#48]
Bitte auf fremde Funktionen,die nicht aus WP kommen nur mit  

` if (function_exists( 'functioname' ) )  {}`

referenzieren.
Also konkret hier:

 ```
   if (function_exists( 'fau_get_ad' ) ) : 
			echo fau_get_ad('werbebanner_seitlich',false);
		    endif; 
```

Die Funktion ist mit dem letzten Update rausgefallen.

https://github.com/ilifau/ili-fau-templates/blob/b7bba67119ec70e9fb24d0b0c66e7c6b3e9415c7/ILI/FAUTemplates/templates/template-landing-page.php#L21

**Comment by xwolfde** [comment]
Problem tritt auch weiter unten im Template auf:
```
grep -rnw './plugins/' -e 'fau_get_ad'
./plugins/ili-fau-templates/ILI/FAUTemplates/templates/template-landing-page.php:21:            <?php  echo fau_get_ad('werbebanner_seitlich',false);  ?>
./plugins/ili-fau-templates/ILI/FAUTemplates/templates/template-landing-page.php:132:            echo fau_get_ad('werbebanner_unten',true);

```

**Comment by SebastianHonert** [comment]
Für alle Funktionen gefixt.
