### ISSUE TITLE
Kritischer Copy&Paste Fehler bei Blogroll

### ISSUE THREAD

**Issue by xwolfde** [ilifau/ili-fau-templates#50]
Ich gehe mal davon aus, daß Zeile 64-66 in template-landing-page.php ein Copy&Paste Fehler ist.

Korrekt muss da rein:
 if( function_exists('fau_display_news_teaser') ) { echo fau_display_news_teaser($post->ID); };

Da dies auf der FAU-Website die Blogroll unsichtbar macht (der Counter der Beiträge wird nämlich auf das Max erhöht, aber nichts angezeigt), wurde dort einstweilen ein Workaround mit einem ungültigen Tag gemacht.

**Comment by SebastianHonert** [comment]
OK, habe ich geändert.
